[project]
name = "glopt"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imageio>=2.37.0",
    "matplotlib>=3.10.3",
    "networkx>=3.5",
    "pulp>=3.2.1",
    "pymupdf>=1.26.3",
    "scipy>=1.16.1",
]

[project.scripts]
glopt-all = "glopt.cli.all:main"
glopt-benchmark = "glopt.cli.benchmark:main"
glopt-dynamic = "glopt.cli.dynamic:main"
glopt-test = "glopt.cli.test:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["glopt*"]

[dependency-groups]
dev = ["black>=25.1.0", "pytest>=8.4.1", "ruff>=0.12.4"]
