[project]
name = "graph-licensing-optimization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "pulp>=3.1.1",
    "pytest>=8.3.5",
]

[tool.ruff]
line-length = 120
