[project]
name = "optimal-license-distribution"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "mip>=1.15.0",
    "networkx>=3.4.2",
    "pyqt6>=6.8.1",
]
