[project]
name = "optimal-license-distribution-api"
version = "0.1.0"
description = "Optimal License Distribution API"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "networkx>=3.4.2",
    "ruff>=0.9.6",
]
