return {
 ["Arial/B:mode=node;language=dflt;#b#655361"]={ "/usr/share/fonts/truetype/msttcorefonts/arialbd.ttf", false },
 ["Arial/B:mode=node;language=dflt;#b#655362"]={ "/usr/share/fonts/truetype/msttcorefonts/arialbd.ttf", false },
 ["Arial/B:mode=node;language=dflt;+tlig;#b#655360"]={ "/usr/share/fonts/truetype/msttcorefonts/arialbd.ttf", false },
 ["Arial/B:mode=node;language=dflt;+tlig;#b#943718"]={ "/usr/share/fonts/truetype/msttcorefonts/arialbd.ttf", false },
 ["Arial/BI:mode=node;language=dflt;#bi#655361"]={ "/usr/share/fonts/truetype/msttcorefonts/arialbi.ttf", false },
 ["Arial/BI:mode=node;language=dflt;#bi#655362"]={ "/usr/share/fonts/truetype/msttcorefonts/arialbi.ttf", false },
 ["Arial/BI:mode=node;language=dflt;+tlig;#bi#655360"]={ "/usr/share/fonts/truetype/msttcorefonts/arialbi.ttf", false },
 ["Arial/BI:mode=node;language=dflt;+tlig;#bi#786432"]={ "/usr/share/fonts/truetype/msttcorefonts/arialbi.ttf", false },
 ["Arial/I:mode=node;language=dflt;#i#655361"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial_Italic.ttf", false },
 ["Arial/I:mode=node;language=dflt;#i#655362"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial_Italic.ttf", false },
 ["Arial/I:mode=node;language=dflt;+tlig;#i#655360"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial_Italic.ttf", false },
 ["Arial:mode=node;#655358"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf", false },
 ["Arial:mode=node;#655362"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf", false },
 ["Arial:mode=node;language=dflt;#655361"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf", false },
 ["Arial:mode=node;language=dflt;#655362"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf", false },
 ["Arial:mode=node;language=dflt;+tlig;#327680"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf", false },
 ["Arial:mode=node;language=dflt;+tlig;#458752"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf", false },
 ["Arial:mode=node;language=dflt;+tlig;#524288"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf", false },
 ["Arial:mode=node;language=dflt;+tlig;#655360"]={ "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf", false },
}